#포트설정
server:
  port: '8586'
#JSP 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#SMTP 설정
  mail:
    host: smtp.gmail.com
    port: '587'
    username: hanilee212@gmail.com
    password: cmqw qhgc okhg neyk
    properties:
      mail:
        debug: 'true'
        smtp:
          connectiontimeout: '5000'
          auth: 'false'
          starttls:
            enable: 'true'
            required: 'true'
